INFO: -N -a -A -D utopic -P -B -T utopic python-service-identity_1.0.0-0ubuntu1.dsc
Using the following defaults:
name: Ubuntu Archive
email: archive@ubuntu.com
Checking: python-service-identity_1.0.0-0ubuntu1.dsc
Mode: archive

Retrieving madison output:      pass
Distribution:                   pass
Pocket:                         pass
Maintainer:                     SKIP (archive)
Changed-By:                     SKIP (archive)
Source has orig.tar.gz:         pass
Recent date:                    SKIP (archive)
Output of diffstat:             SKIP (could not find debdiff or diff.*)
Vcs files in diffstat:          No such file or directory
pass
Vcs files in patch files:       SKIP: could not find 'python-service-identity_1.0.0-0ubuntu1.debdiff'
Version:                        SKIP (initial release?)
Newest version:                 FAIL
 Current: 1.0.0-0ubuntu1
 Found:   1.0.0-0ubuntu2
Diff chaff:                     pass
Merged changelog:               FAIL: revisions from 1.0.0-0ubuntu2
Changelog autocloses LP bugs:   pass
Patch system:                   SKIP: (diff not specified)
Patch tagging:                  SKIP: (diff not specified)
Check bashisms in 'debian':     pass
Reverse Debdiff:                SKIP: could not find 'python-service-identity_1.0.0-0ubuntu1.debdiff'
Bad files:                      pass
Vcs files in source:            pass
Ubuntu archive:
  python-service-identity | 1.0.0-0ubuntu2 | utopic/universe | source, all
Debian archive:
 Not found in Debian testing, unstable or experimental

Has debian/watch:               pass
Output of lintian:              pass
Output of licensecheck:         WARNING: no known copyrights found
Output of suspicious-source:    pass (empty)
Check bashisms in '.':          pass (skipped ./configure and ./config.guess)
chmod/chown in debian/:         pass
bash network redirections:      pass
/bin/sh as shell in debian/:    pass
Upstream source:                https://pypi.python.org/pypi/service_identity
Source build:                    dpkg-buildpackage -rfakeroot -d -us -uc -S
dpkg-buildpackage: source package python-service-identity
dpkg-buildpackage: source version 1.0.0-0ubuntu1
dpkg-buildpackage: source distribution utopic
dpkg-buildpackage: source changed by Matthias Klose <doko@ubuntu.com>
 dpkg-source --before-build source_build
 fakeroot debian/rules clean
dh clean --with python2,python3 --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:170: python2.7 setup.py clean 
running clean
removing '/home/sarnold/ubuntu/security/audits/python-service-identity/utopic/source/tmp.ZUV6Cq07AU/source_build/.pybuild/pythonX.Y_2.7/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
I: pybuild base:170: python3.4 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
E: pybuild pybuild:256: clean: plugin distutils failed with: exit code=1: python3.4 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p 3.4 --dir . returned exit code 13
make: *** [clean] Error 13
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -d -us -uc -S failed
FAIL

Statistics:
 Size (unpacked): 1M
 Number files: 39
 Number directories: 7
 Number symlinks: 0
 Estimated lines of source: 1445
Check existing binaries (may take a while): 
 found existing: python-service-identity utopic/universe
 found existing: python3-service-identity utopic/universe
 Total: 2 (new=0, existing=2)
------
FAILED
