INFO: -N -a -A -D yakkety -P -B -T yakkety python-ws4py_0.3.4-3.dsc
Using the following defaults:
name: Ubuntu Archive
email: archive@ubuntu.com
Checking: python-ws4py_0.3.4-3.dsc
Mode: archive

Retrieving madison output:      pass
Distribution:                   pass
Pocket:                         pass
Maintainer:                     SKIP (archive)
Changed-By:                     SKIP (archive)
Source has orig.tar.gz:         pass
Recent date:                    SKIP (archive)
Output of diffstat:             SKIP (could not find debdiff or diff.*)
Vcs files in diffstat:          No such file or directory
pass
Vcs files in patch files:       SKIP: could not find 'python-ws4py_0.3.4-3.debdiff'
Version:                        SKIP (initial release?)
Newest version:                 FAIL
 Current: 0.3.4-3
 Found:   0.3.4-3
Diff chaff:                     pass
Merged changelog:               ignored
Changelog autocloses LP bugs:   pass
Patch system:                   SKIP: (diff not specified)
Patch tagging:                  SKIP: (diff not specified)
Check bashisms in 'debian':     pass
Reverse Debdiff:                SKIP: could not find 'python-ws4py_0.3.4-3.debdiff'
Bad files:                      pass
Vcs files in source:            INFO: found VCS files, please verify:
./.gitignore
./debian/.git-dpm

Ubuntu archive:
  python-ws4py | 0.3.4-3 | yakkety/universe | source, all
Debian archive:
 python-ws4py | 0.3.4-2       | testing         | source, all
 python-ws4py | 0.3.4-3       | unstable        | source, all

Has debian/watch:               pass
Output of lintian:              
 W: python-ws4py source: newer-standards-version 3.9.8 (current is 3.9.7)

Output of licensecheck:         
 Unique licenses:
  Apache (v2.0)
  BSD (3 clause)
  GENERATED FILE
  UNKNOWN

 Full output:
  debian/changelog: UNKNOWN
  debian/copyright: BSD (3 clause)
  docs/conf.py: GENERATED FILE
  ws4py/utf8validator.py: Apache (v2.0)

Output of suspicious-source:    pass (empty)
Check bashisms in '.':          pass (skipped ./configure and ./config.guess)
chmod/chown in debian/:         pass
bash network redirections:      pass
/bin/sh as shell in debian/:    pass
Upstream source:                https://ws4py.readthedocs.org/
Source build:                    dpkg-buildpackage -rfakeroot -d -us -uc -S
dpkg-buildpackage: source package python-ws4py
dpkg-buildpackage: source version 0.3.4-3
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Stein Magnus Jodal <jodal@debian.org>
 dpkg-source --before-build source_build
 fakeroot debian/rules clean
dh clean --with python2,python3,sphinxdoc --buildsystem=pybuild
dh: unable to load addon sphinxdoc: Can't locate Debian/Debhelper/Sequence/sphinxdoc.pm in @INC (you may need to install the Debian::Debhelper::Sequence::sphinxdoc module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at (eval 15) line 2.
BEGIN failed--compilation aborted at (eval 15) line 2.

debian/rules:11: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -d -us -uc -S failed
FAIL

Statistics:
 Size (unpacked): 1M
 Number files: 101
 Number directories: 21
 Number symlinks: 0
 Estimated lines of source: 6848
Check existing binaries (may take a while): 
 found existing: python-ws4py yakkety/universe
 found existing: python3-ws4py yakkety/universe
 Total: 2 (new=0, existing=2)
------
FAILED
