Candidate: CVE-2010-3493
PublicDate: 2010-10-19
References:
 http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3493
Description:
 Multiple race conditions in smtpd.py in the smtpd module in Python 2.6,
 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service
 (daemon outage) by establishing and then immediately closing a TCP
 connection, leading to the accept function having an unexpected return
 value of None, an unexpected value of None for the address, or an
 ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function
 having an ENOTCONN error, a related issue to CVE-2010-3492.
Ubuntu-Description:
Notes:
Bugs:
Priority: negligible
Discovered-by:
Assigned-to:

Patches_python3.2:
upstream_python3.2: needs-triage
dapper_python3.2: DNE
hardy_python3.2: DNE
jaunty_python3.2: DNE
karmic_python3.2: DNE
lucid_python3.2: DNE
maverick_python3.2: DNE
natty_python3.2: needs-triage
devel_python3.2: needs-triage

Patches_python2.7:
upstream_python2.7: needs-triage
dapper_python2.7: DNE
hardy_python2.7: DNE
jaunty_python2.7: DNE
karmic_python2.7: DNE
lucid_python2.7: DNE
maverick_python2.7: needs-triage
natty_python2.7: needs-triage
devel_python2.7: needs-triage

Patches_python3.1:
upstream_python3.1: needs-triage
dapper_python3.1: DNE
hardy_python3.1: DNE
jaunty_python3.1: DNE
karmic_python3.1: needs-triage
lucid_python3.1: needs-triage
maverick_python3.1: needs-triage
natty_python3.1: needs-triage
devel_python3.1: needs-triage
