Candidate: CVE-2013-1752
PublicDate: 2013-12-26
References:
 http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1752
 http://marc.info/?l=oss-security&m=138816139322814&w=2
 http://marc.info/?l=oss-security&m=138784213903127&w=2
 http://www.openwall.com/lists/oss-security/2013/12/26
Description:
 Multiple DoS issues when connecting to untrusted servers
Ubuntu-Description:
Notes:
Bugs:
 https://bugzilla.redhat.com/show_bug.cgi?id=1046174
 http://bugs.python.org/issue16037
 http://bugs.python.org/issue16038
 http://bugs.python.org/issue16039
 http://bugs.python.org/issue16040
 http://bugs.python.org/issue16041
 http://bugs.python.org/issue16042
 https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1351180
Priority: low
Discovered-by:
Assigned-to: mdeslaur

Patches_python2.7:
upstream_python2.7: needs-triage
lucid_python2.7: DNE
precise_python2.7: needed
quantal_python2.7: ignored (reached end-of-life)
raring_python2.7: ignored (reached end-of-life)
saucy_python2.7: ignored (reached end-of-life)
trusty_python2.7: needed
utopic_python2.7: needed
vivid_python2.7: needed
devel_python2.7: needed

Patches_python3.2:
upstream_python3.2: needs-triage
lucid_python3.2: DNE
precise_python3.2: needed
quantal_python3.2: ignored (reached end-of-life)
raring_python3.2: DNE
saucy_python3.2: DNE
trusty_python3.2: DNE
utopic_python3.2: DNE
vivid_python3.2: DNE
devel_python3.2: DNE

Patches_python3.4:
upstream_python3.4: needs-triage
lucid_python3.4: DNE
precise_python3.4: DNE
quantal_python3.4: DNE
raring_python3.4: DNE
saucy_python3.4: DNE
trusty_python3.4: not-affected
utopic_python3.4: not-affected
vivid_python3.4: not-affected
devel_python3.4: not-affected

