Candidate: CVE-2019-9948
PublicDate: 2019-03-23
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9948
 https://bugs.python.org/issue35907
 https://github.com/python/cpython/pull/11842
Description:
 urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which
 makes it easier for remote attackers to bypass protection mechanisms that
 blacklist file: URIs, as demonstrated by triggering a
 urllib.urlopen('local_file:///etc/passwd') call.
Ubuntu-Description:
Notes:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:


Patches_python2.7:
upstream_python2.7: needs-triage
precise/esm_python2.7: needs-triage
trusty_python2.7: needed
xenial_python2.7: needed
bionic_python2.7: needed
cosmic_python2.7: needed
devel_python2.7: needed
