Candidate: CVE-2019-9948
PublicDate: 2019-03-23
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9948
 https://github.com/python/cpython/pull/11842
Description:
 urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which
 makes it easier for remote attackers to bypass protection mechanisms that
 blacklist file: URIs, as demonstrated by triggering a
 urllib.urlopen('local_file:///etc/passwd') call.
Ubuntu-Description:
Notes:
 mdeslaur> as of 2019-04-10, patch not in upstream repo yet
Bugs:
 https://bugs.python.org/issue35907
Priority: medium
Discovered-by: Sihoon Lee
Assigned-to: mdeslaur


Patches_python2.7:
upstream_python2.7: released (2.7.16-2)
precise/esm_python2.7: needs-triage
trusty_python2.7: ignored (reached end-of-life)
trusty/esm_python2.7: needed
xenial_python2.7: needed
bionic_python2.7: needed
cosmic_python2.7: pending (2.7.16-2~18.10)
disco_python2.7: not-affected (2.7.16-2)
devel_python2.7: not-affected (2.7.16-2)
