Candidate: CVE-2011-4137
PublicDate: 2011-10-19
References:
 http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-4137
Description:
 The verify_exists functionality in the URLField implementation in Django
 before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt
 access to an arbitrary URL with no timeout, which allows remote attackers
 to cause a denial of service (resource consumption) via a URL associated
 with (1) a slow response, (2) a completed TCP connection with no
 application data sent, or (3) a large amount of application data, a related
 issue to CVE-2011-1521.
Ubuntu-Description:
Notes:
Bugs:
Priority: medium
Discovered-by: Paul McMillan
Assigned-to: jdstrand

Patches_python-django:
 upstream: https://code.djangoproject.com/changeset/16766 (1.2)
 upstream: https://code.djangoproject.com/changeset/16763 (1.3)
upstream_python-django: released (1.3.1-1)
hardy_python-django: ignored (reached end-of-life)
lucid_python-django: needed
maverick_python-django: needed
natty_python-django: needed
oneiric_python-django: needed
devel_python-django: not-affected (1.3.1-1ubuntu1)
