Candidate: CVE-2020-1747
PublicDate: 2020-03-03 00:00:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1747
 https://github.com/yaml/pyyaml/pull/386
Description:
 [arbitrary command execution through python/object/new when FullLoader is
 used]
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953013
Priority: medium
Discovered-by:
Assigned-to:


Patches_pyyaml:
upstream_pyyaml: needs-triage
precise/esm_pyyaml: needs-triage
trusty_pyyaml: ignored (out of standard support)
trusty/esm_pyyaml: needs-triage
xenial_pyyaml: needs-triage
bionic_pyyaml: needs-triage
eoan_pyyaml: needs-triage
devel_pyyaml: needs-triage
