Candidate: CVE-2019-11324
PublicDate: 2019-04-18
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11324
 https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4
 https://www.openwall.com/lists/oss-security/2019/04/17/3
 http://www.openwall.com/lists/oss-security/2019/04/19/1
Description:
 The urllib3 library before 1.24.2 for Python mishandles certain cases where
 the desired set of CA certificates is different from the OS store of CA
 certificates, which results in SSL connections succeeding in situations
 where a verification failure is the correct outcome. This is related to use
 of the ssl_context, ca_certs, or ca_certs_dir argument.
Ubuntu-Description:
Notes:
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927412
Priority: medium
Discovered-by:
Assigned-to:


Patches_python-urllib3:
upstream_python-urllib3: needs-triage
precise/esm_python-urllib3: DNE
trusty_python-urllib3: needs-triage
trusty/esm_python-urllib3: needs-triage
xenial_python-urllib3: needs-triage
bionic_python-urllib3: needs-triage
cosmic_python-urllib3: needs-triage
disco_python-urllib3: needs-triage
devel_python-urllib3: needs-triage
